name: polaris_citizen
description: Citizen-facing Flutter app for Polaris.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.0
  image_picker: ^1.1.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
